name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 监听 main 分支的提交

# 给 Actions 写入 Pages 的权限
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # 告诉 GitHub 将编译生成的 dist 目录作为网页部署

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
